name: ripple_image_button
description: "simple using image button, has ripple effect."
version: 1.0.5
homepage: "https://cavedwellers.co.kr"
repository: "https://github.com/b3lon9/RippleImageButton"

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
